POST http://localhost:9000/graphql
Content-Type: application/json

{
    "query": "query {tours {city}}"
}

###

GET http://localhost:5000/graphql?query=%7B%0A%20%20tours%20%7B%0A%20%20%20%20city%0A%20%20%7D%0A%7D%0A

###

GET https://jsonplaceholder.typicode.com/todos/1

###